### ISSUE TITLE
Problem displaying Screenshot in news post

### ISSUE THREAD

**Issue by theapplegates** [nhoizey/pack11ty#11]
I am having trouble displaying the screenshot on this page, https://pack11ty.dev/news/2020/04/14/layout-and-design/

I noticed the URL had an error. It showed https://res.cloudinary.com/paulportfolio/image/fetch/q_auto,f_auto,w_1600,c_limit/https://gifted-hermann-0987c3.netlify.app//news/2020/04/14/layout-and-design/pack11ty-screenshot.png
, note the 2 forward slashes after app not just 1 like it should be, so I removed the trailing slash in the package.json URL, and the URL now seems correct, https://res.cloudinary.com/paulportfolio/image/fetch/q_auto,f_auto,w_1600,c_limit/https://gifted-hermann-0987c3.netlify.app/news/2020/04/14/layout-and-design/pack11ty-screenshot.png
but the image does not show. I also removed your NHO from the Cloudinary URL in images-responsiver-config.js and put my own in.

What am I doing wrong? The image shows up fine when I run it locally.

**Comment by nhoizey** [comment]
What a coincidence!

I also had the issue on https://pack11ty.dev and fixed it a few minutes ago:
https://github.com/nhoizey/pack11ty/commit/af0c516cbc113f3c3fe9d02f4772e9f9c5f38964

Also, did you add `gifted-hermann-0987c3.netlify.app` to the "Allowed fetch domains" in Cloudinary security settings?

**Comment by theapplegates** [comment]
I'll download it again and check.
I did allow it, and just turned it off and allowed anyone to fetch to troubleshoot. No effect on it.

**Comment by nhoizey** [comment]
The URL looks fine indeed.

Could you try remove all versions of the image from your Cloudinary library and retry?

**Comment by theapplegates** [comment]
as another FYI, your netlify.toml does not have any info such as build command and publish path. I put them in manually and usually they auto populate.

Yes, I will remove and re-try

**Comment by theapplegates** [comment]
So this works, with your name in the URL
https://res.cloudinary.com/nho/image/fetch/q_auto,f_auto,w_1600,c_limit/https://pack11ty.dev/news/2020/04/14/layout-and-design/pack11ty-screenshot.png

Mine does not work

https://res.cloudinary.com/paulportfolio/image/fetch/q_auto,f_auto,w_1600,c_limit/https://pack11ty.dev/news/2020/04/14/layout-and-design/pack11ty-screenshot.png

I deleted the image also

It has to be a permission/setup issue on my end. I will troubleshoot in a few, I have to go out for a bit.

**Comment by nhoizey** [comment]
> as another FYI, your netlify.toml does not have any info such as build command and publish path. I put them in manually and usually they auto populate.

You're right, thanks!

Fixed in https://github.com/nhoizey/pack11ty/commit/5264231d0fd1d47e875095011c81420dd5c029c8

**Comment by theapplegates** [comment]
Fixed it. I had Fetch Checked, it should not be checked. 
<img width="723" alt="Screen Shot 2020-04-29 at 11 03 11 AM" src="https://user-images.githubusercontent.com/27178137/80611844-277c0780-8a09-11ea-8b9a-7ef3aa83f062.png">

**Comment by theapplegates** [comment]
Fetched URL checked I meant.
Thanks for your help again.

**Comment by nhoizey** [comment]
Great to know it's fixed! 👍
