### ISSUE TITLE
missing home meta description (getting a google lighthouse penalty)

### ISSUE THREAD

**Issue by stoqe** [nhoizey/pack11ty#14]
- love this starter
- thanks for making it available
- i noticed when admiring the google lighthouse scores there was a minor matter with the seo score
- as per the google lighthouse details: "Document does not have a meta description. Description text is empty."
- i would submit a pull request fix but i don't quite understand the logic with pack11ty's site/global data? most 11ty themes/starter seem to use a site.json file for global but it looks like pack11ty is taking a different approach? (though it's 1:30am where i am atm, so maybe i'm just too tired to see it?)

**Comment by nhoizey** [comment]
Thanks for the issue @stoqe, sorry for the very late reaction.

You're right, the description is missing, I'll fix that.

You're also right that I did take another approach for site data, but I'm considering following the more common way of others, as it eases adoption: #15
