### ISSUE TITLE
Error while executing

### ISSUE THREAD

**Issue by stoqe** [nhoizey/pack11ty#9]
hello and thanks for making pack11ty, can't wait to use it. 

- i'm having an issue installing pack11ty
- both "deploy to netlfiy" and local builds fail
- both netlfiy and local seem to be having issues with missing folders

locally "npm install" rendors the following error message

- npm ERR! Error while executing:
- npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/11ty/eleventy.git
- npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
- npm ERR! exited with error code: 1

screenshot of some early warning signs too
![pack11ty-error](https://user-images.githubusercontent.com/1171169/80465514-8fd1d700-897e-11ea-8b6a-c1ce080b99ce.png)

**Comment by stoqe** [comment]
- i take it all back!
- i'm not sure what's was going on
- but i deleted everything and started again (for the 2nd time; i tried that once already before filing an issue)
- and now everything installs and runs fine (locally & on netlify)

**Comment by nhoizey** [comment]
@stoqe I see the issue was coming from Command Line Tools.

Maybe you had an issue similar to what's in https://github.com/nhoizey/pack11ty/issues/3#issuecomment-614773074
